config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do
  resources :contacts
  constraints(SubdomainPresent) do
    root 'contacts#index', as: :subdomain_root
    devise_for :users
    resources :users, only: :index
  end

  constraints(SubdomainBlank) do
    root "welcome#index"
    resources :accounts, only: [:new, :create]
  end
end

app/models/account.rb
 class Account < ActiveRecord::Base
    RESTRICTED_SUBDOMAINS = %w(www)
  
    belongs_to :owner, class_name: "User"
    validates :owner, presence: true
    validates :subdomain, presence: true,
                          uniqueness: { case_sensitive: false },
                          format: { with: /\A[\w\-]+\Z/i, message: 'contains invalid characters' },
                          exclusion: { in: RESTRICTED_SUBDOMAINS, message: 'restricted' }
  
    accepts_nested_attributes_for :owner
    before_validation :downcase_subdomain
  
  private
   def downcase_subdomain
     self.subdomain = subdomain.try(:downcase)
   end
 end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/user.rb
   class User < ApplicationRecord
   # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :invitable, :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
 
          validates :name, presence: true
  end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
   skip_before_filter :authenticate_user!, only: [:new, :create]
    def new
      @account = Account.new
      @account.build_owner
    end
  
    def create
      @account = Account.new(account_params)
     if @account.valid?
       Apartment::Database.create(@account.subdomain)
       Apartment::Database.switch(@account.subdomain)
       @account.save
       redirect_to new_user_session_url(subdomain: @account.subdomain)
      else
        render action: 'new'
      end
   end
 
 private
   def account_params
     params.require(:account).permit(:subdomain, owner_attributes: [:name, :email, :password, :password_confirmation])
   end
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :load_schema, :authenticate_user!, :set_mailer_host
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:accept_invitation).concat([:name])
  end
  
  private

  def load_schema
    Apartment::Database.switch('public')
    return unless request.subdomain.present?

    if current_account
      Apartment::Database.switch(current_account.subdomain)
    else
      redirect_to root_url(subdomain: false)
    end
  end

  def current_account
    @current_account ||= Account.find_by(subdomain: request.subdomain)
  end
  helper_method :current_account

  def set_mailer_host
    subdomain = current_account ? "#{current_account.subdomain}." : ""
    ActionMailer::Base.default_url_options[:host] = "#{subdomain}lvh.me:3000"
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end

  def after_invite_path_for(resource)
    users_path
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :company, :notes)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   def index
     @users = User.all
   end
 end

app/controllers/welcome_controller.rb
 class WelcomeController < ApplicationController
   skip_before_filter :authenticate_user!, only: :index
    def index
    end
  end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/user_helper.rb
 module UserHelper
    def user_status(user)
     if current_account.owner == user || user.invitation_accepted?
        content_tag(:span, '', class: 'glyphicon glyphicon-ok color-success')
      else
        'Invitation Pending'
     end
   end
 end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/accounts/new.html.erb
<div class="col-md-6 col-md-offset-3 panel panel-default">
  <div class="panel-body">
     <h2>Create an Account</h2>

     <%= simple_form_for @account do |f| %>
    <%= f.fields_for :owner do |o| %>
      <%= o.input :name, class: "form-control", required: true, label: "Your Name" %>
      <%= o.input :email, class: "form-control", required: true %>
      <%= o.input :password, class: "form-control", required: true %>
      <%= o.input :password_confirmation, class: "form-control", required: true %>
    <% end %>
    <%= f.label :subdomain %>
     <div class="input-group">
           <%= f.input :subdomain, class: 'form-control', label: false %>
           <span class="input-group-addon" id="basic-addon2">.simplepipe.xyz</span>
        </div>
        <br>
      <%= f.submit class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :company %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Company</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.company %></td>
        <td><%= contact.notes %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Company:</strong>
  <%= @contact.company %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @contact.notes %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Simplepipe", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

       <ul class="nav navbar-nav navbar-right">
         <% if current_user %>
          <li><%= link_to "Users", users_path %></li>
         <li><%= link_to "Settings", edit_user_registration_path %></li>
         <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
         <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimplePipe</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "layouts/navbar" %>
  <% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/index.html.erb
<div class="col-md-8 col-md-offset-2">
   <h2>Authorized Users</h2>

   <div class="panel panel-default">
     <div class="panel-body">
       <table class="table table-striped">
         <thead>
           <tr>
             <th>Name</th>
             <th>Email</th>
             <th>Status</th>
           </tr>
         </thead>
         <tbody>
           <% @users.each do |user| %>
             <tr>
               <td><%= user.name %></td>
               <td><%= user.email %></td>
               <td><%= user_status(user) %></td>
             </tr>
            <% end %>
          </tbody>
        </table>

       <h3 class="extra-margin-top">Invite User</h3>

       <%= simple_form_for(User.new, url: user_invitation_path,
                                     html: { class: 'form-inline' }) do |f| %>
         <%= f.input :email, placeholder: 'Email', label: false %>
         <%= f.button :submit, 'Invite User', class: 'btn-primary' %>
       <% end %>
      </div>
    </div>
  </div>

app/views/welcome/index.html.erb
 <div class="row">
 <div class="col-md-12">
   <div class="jumbotron">
     <h1>Simple Pipe</h1>
     <p>The best way to manage your contacts with your team</p>
     <p><%= link_to "Create Account", new_account_path, class: 'btn btn-primary btn-lg' %></p>
   </div>
 </div>
 </div>